### PR TITLE
Setuptools 26.1.1

### PR DESCRIPTION
**Pull request by jgmize**
This builds on #3960 but installs setuptools 26.1.1 without hash verification in `Dockerfile-base` as a workaround for the `AttributeError: 'Requirement' object has no attribute 'project_name'` error we get when attempting to use hash verification.

### CODE REVIEW

**Comment by jgmize** [comment]
@jwhitlock r?

**Comment by safwanrahman** [comment]
Just a note, this Error will only raise with ``pip 8.1.2``
so if you change to a lower version, it will not raise!

**Comment by jwhitlock** [comment]
@safwanrahman the pip version installed is pip 8.1.1, also doesn't work.

This worked for me, with some trial and error. Recreating my command line (so I might have gotten something wrong):

```
$ git fetch jgmize
$ git checkout setuptools-26.1.1
$ make build-base
$ docker tag 27f7a89 quay.io/mozmar/kuma_base:latest
$ make build-kuma
$ docker tag 35a6d393fcec quay.io/mozmar/kuma:latest
$ docker-compose up
$ docker exec -it kuma_web_1 /bin/bash
# ./manage.py migrate
# ./manage.py update_product_details -f
# pip install django-babel==0.4.0
# make localeextract  # Success!
# <Ctrl-D to exit>
# docker restart kuma_web_1  # http://localhost:8000/en-US/ works w/o server error
```

I'll refine the fresh start commands as I write the docs.

**Comment by jgmize** [comment]
This specific backwards incompatibility issue also affects pip 8.1.1-2ubuntu0.1, see https://github.com/peterbe/hashin/pull/23#issue-157047068 and https://github.com/pypa/pip/issues/3687 for more background.
