### PR TITLE
bug 1282146 - Use the new url for the RabbitMQ GPG key

### PR DESCRIPTION
**Pull request by jbradberry**
Use the current master from the Mayeu.RabbitMQ github repo.

The public GPG key for the RabbitMQ repo has moved to a new url
(https://www.rabbitmq.com/rabbitmq-release-signing-key.asc).  The
Mayeu/ansible-playbook-rabbitmq Github repo has been updated to use
the new url, but this fix has not yet made it into an Ansible Galaxy
release.

fix bug 1282146

### CODE REVIEW

**Comment by jwhitlock** [comment]
This fails for me with ansible 2.1.0. Error w/ some reformatting:

```
TASK [Mayeu.RabbitMQ : add rabbitmq user and set privileges] *******************
failed: [developer-local] (item=
{
  u'node': u'rabbit@developer-local',
  u'vhost': u'kuma',
  u'password': u'kuma',
  u'user': u'kuma'
}) => {
  "failed": true, 
  "item": {"node": "rabbit@developer-local", "password": "kuma", "user": "kuma", "vhost": "kuma"},
  "module_stderr": "",
   "module_stdout": "
Traceback (most recent call last):\r\n
  File \"/tmp/ansible_hIjhC9/ansible_module_rabbitmq_user.py\", line 302, in <module>\r\n
    main()\r\n
  File \"/tmp/ansible_hIjhC9/ansible_module_rabbitmq_user.py\", line 274, in main\r\n
    if rabbitmq_user.get():\r\n
  File \"/tmp/ansible_hIjhC9/ansible_module_rabbitmq_user.py\", line 155, in get\r\n
    users = self._exec(['list_users'], True)\r\n
  File \"/tmp/ansible_hIjhC9/ansible_module_rabbitmq_user.py\", line 150, in _exec\r\n
    rc, out, err = self.module.run_command(cmd + args, check_rc=True)\r\n
  File \"/tmp/ansible_hIjhC9/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1993, in run_command\r\n
  File \"/usr/lib/python2.7/posixpath.py\", line 261, in expanduser\r\n
    if not path.startswith('~'):\r\n
AttributeError: 'list' object has no attribute 'startswith'\r\n
",
   "msg": "MODULE FAILURE",
   "parsed": false}
	to retry, use: --limit @provisioning/vagrant.retry
```

Did it work for you? What ansible version?

**Comment by jbradberry** [comment]
@jwhitlock It succeeded for me with Ansible 2.0.1.0.

**Comment by jbradberry** [comment]
@jwhitlock Looks like https://github.com/ansible/ansible-modules-extras/pull/2310 ?

**Comment by jwhitlock** [comment]
@jbradberry yep, that smells familiar.  Trying again w/ 2.0.1.0

**Comment by jwhitlock** [comment]
Works with 2.0.1.0 and 1.9.2. Thanks!
